title: Shantanu Alshi's Blog
email: shantanuals@gmail.com
description: "" 
baseurl: "" 
url: https://blog.shantanualshi.com 
twitter_username: shantanualshi
github_username: shantanualsi 

# Build settings
theme: minima
plugins:
  - jekyll-feed

